version: "3.6"
x-config:
  &config
  restart: 'always'

services:
  api:
    << : *config
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=${NODE_ENDPOINT:-http://172.16.239.1:8545}
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      - epirus
    mem_limit: 1024M
    mem_reservation: 512M

  mongodb:
    << : *config
    image: mongo:latest
    ports:
      - 27017:27017
    entrypoint: mongod --logpath=/dev/null --bind_ip "0.0.0.0"
    networks:
      - epirus
    mem_limit: 1024M
    mem_reservation: 512M

  web:
    << : *config
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
    depends_on:
      - api
    networks:
      - epirus
  
  ingestion:
    << : *config
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=${NODE_ENDPOINT:-http://172.16.239.1:8545}
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      - epirus
    mem_limit: 1024M
    mem_reservation: 512M
      
  nginx:
    << : *config
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 80:80
    depends_on:
      - api
      - web
    networks:
      - epirus

networks:
  epirus:
    name: epirus-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
